version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: auth-sgbd
      MYSQL_USER: fslab
      MYSQL_PASSWORD: fslab
      MYSQL_ROOT_PASSWORD: fslab
    expose:
      - "3306"
    ports:
      - "3306:3306"
    